name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install
      - run: yarn lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build

      - run: yarn test:cypress

      - run: yarn test:jest --coverage
        env:
          CI: true

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: JS-DevTools/npm-publish@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          tag: latest
          access: public
          dry-run: false
          check-version: true
          greater-version-only: true
