name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - run: yarn install
      - run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - run: yarn install
      - run: yarn build

      - run: yarn test:cypress

      - run: yarn test:jest --coverage
        env:
          CI: true

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: JS-DevTools/npm-publish@v2
        id: publish
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          tag: latest
          access: public
          dry-run: false
          strategy: all

      - name: Tag
        if: github.ref_name == 'main' && steps.publish.outputs.type
        uses: anothrNick/github-tag-action@v1
        env:
          CUSTOM_TAG: ${{ steps.publish.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: github.ref_name == 'main' && steps.publish.outputs.type
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          body:
            'Changelog: https://github.com/iendeavor/vue-next-select/blob/${{ steps.publish.outputs.version
            }}/CHANGELOG.md'
