name: Release

on:
  schedule:
    - cron: '0 6 * * 3'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Test
        run: |
          yarn run test:cypress
          yarn run test:jest

      - name: Release
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          yarn run release

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          reviewers: 'iendeavor'
